# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Subtask < Formula
  desc "Parallel task orchestration for AI coding agents."
  homepage "https://github.com/zippoxer/subtask"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zippoxer/subtask/releases/download/v0.1.0/subtask_0.1.0_darwin_amd64.tar.gz"
      sha256 "2bd5f8bb18293dcabdee9bacaa90f85e864002d2f360847215f0eab439081aa1"

      def install
        bin.install "subtask"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zippoxer/subtask/releases/download/v0.1.0/subtask_0.1.0_darwin_arm64.tar.gz"
      sha256 "a50acf3ab7a84f244191d2649100d0f99b3133fdf89a5be7dc7d52f0dfe8ffc3"

      def install
        bin.install "subtask"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zippoxer/subtask/releases/download/v0.1.0/subtask_0.1.0_linux_amd64.tar.gz"
      sha256 "389f2d5e689d5349b3452de4711862dd55269fe912176d5d5c60a7f995a0fa30"
      def install
        bin.install "subtask"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zippoxer/subtask/releases/download/v0.1.0/subtask_0.1.0_linux_arm64.tar.gz"
      sha256 "2b87de79582bb323773936f94d3081b70b8a9e6dd6030c83bd929d1a4dcdcca6"
      def install
        bin.install "subtask"
      end
    end
  end

  test do
    system "#{bin}/subtask", "--version"
  end
end
