# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Subtask < Formula
  desc "Parallel task orchestration for AI coding agents."
  homepage "https://github.com/zippoxer/subtask"
  version "0.0.1-test2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zippoxer/subtask/releases/download/v0.0.1-test2/subtask_0.0.1-test2_darwin_amd64.tar.gz"
      sha256 "a1cd40e92dad8bd76c2d49e90dcef7e88a7d04646155c84fc573b2f1fd9e4895"

      def install
        bin.install "subtask"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zippoxer/subtask/releases/download/v0.0.1-test2/subtask_0.0.1-test2_darwin_arm64.tar.gz"
      sha256 "7d1142989810bd80feeab19a215aac1f17eee6c3dfee04c4e633cf03ded60c00"

      def install
        bin.install "subtask"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zippoxer/subtask/releases/download/v0.0.1-test2/subtask_0.0.1-test2_linux_amd64.tar.gz"
      sha256 "8ea50a3fbed433a8c241dd31e604821625000ae41b1e95788bf3fca1c40175af"
      def install
        bin.install "subtask"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zippoxer/subtask/releases/download/v0.0.1-test2/subtask_0.0.1-test2_linux_arm64.tar.gz"
      sha256 "73b87df35db4ea4b3740ea6232b8efaed47fe843bf471b42e9f9b81d9e81199d"
      def install
        bin.install "subtask"
      end
    end
  end

  test do
    system "#{bin}/subtask", "--version"
  end
end
