# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Subtask < Formula
  desc "Parallel task orchestration for AI coding agents."
  homepage "https://github.com/zippoxer/subtask"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zippoxer/subtask/releases/download/v0.3.0/subtask_0.3.0_darwin_amd64.tar.gz"
      sha256 "97dc0e63ea4a6530287bcc67bd0934c710a720760beb14d40b25dd1f9313ad31"

      def install
        bin.install "subtask"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zippoxer/subtask/releases/download/v0.3.0/subtask_0.3.0_darwin_arm64.tar.gz"
      sha256 "b2ca8991a299faa4d3de5a471738de49a1a28e38c5021481500e4f534e2acb3d"

      def install
        bin.install "subtask"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zippoxer/subtask/releases/download/v0.3.0/subtask_0.3.0_linux_amd64.tar.gz"
      sha256 "698d2da60970486db8b143a1dce4712be3c765a01c673bd77b6e0d7ca138a293"
      def install
        bin.install "subtask"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zippoxer/subtask/releases/download/v0.3.0/subtask_0.3.0_linux_arm64.tar.gz"
      sha256 "f2e1f7d2080a4f918af3c61860c0caa30a5c911877b86a92aeebdb27e5ad6be0"
      def install
        bin.install "subtask"
      end
    end
  end

  test do
    system "#{bin}/subtask", "--version"
  end
end
