# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Subtask < Formula
  desc "Parallel task orchestration for AI coding agents."
  homepage "https://github.com/zippoxer/subtask"
  version "0.4.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zippoxer/subtask/releases/download/v0.4.1/subtask_0.4.1_darwin_amd64.tar.gz"
      sha256 "e4a3f425ad200442ba69fe0a95df5d5217840dafb158e9a20f5a9455edf58ddc"

      def install
        bin.install "subtask"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zippoxer/subtask/releases/download/v0.4.1/subtask_0.4.1_darwin_arm64.tar.gz"
      sha256 "a2fe62e77807cff8be1f39869fc5910f45bfd389a3c3532a5ff1c79afc70150b"

      def install
        bin.install "subtask"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zippoxer/subtask/releases/download/v0.4.1/subtask_0.4.1_linux_amd64.tar.gz"
      sha256 "26084c8ecdd95a812a104c5d7dc06fc6376e64f450700cdf4f3e92ad59c32e68"
      def install
        bin.install "subtask"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zippoxer/subtask/releases/download/v0.4.1/subtask_0.4.1_linux_arm64.tar.gz"
      sha256 "df0da5d29f0ef7661c71ea6914fad5ef5e3b72e0b5114be1f139c9eeca590402"
      def install
        bin.install "subtask"
      end
    end
  end

  test do
    system "#{bin}/subtask", "--version"
  end
end
